[DO NOT MERGE] test pipeline
mendersoftware/mender-artifact pull request #434
Opened 2022-10-10 17:04 UTC by 0lmi

2022-10-11 10:04 UTC, 0lmi commented
@mender-test-bot start pipeline

2022-10-11 11:33 UTC, oleorhagen reviewed
It looks to me like we can solve this using our already existing binary instrumentation for collecting coverage.

If you want me to give you a quick run-through of this, just ping me :)

2022-10-11 11:33 UTC, oleorhagen commented on main_test.go
> +	log.Log.ExitFunc = func(int) {}
Question: Why do we need `go-lib-micro` here?

2022-10-11 11:40 UTC, oleorhagen requested changes
After a quick f2f we decided the already existing binary-instrumentation for test-coverage is plenty here

2022-10-12 10:20 UTC, 0lmi commented
Alternative implementation using `gobinarycoverage` https://github.com/mendersoftware/mender-artifact/pull/435

2022-10-17 08:31 UTC, 0lmi commented
@oleorhagen if to be honest I think this approach is more unified than using `gobinarycoverage` due to it's used everywhere else (mender-cli, all backend services...). Obviously the result is the same, but unification is valuable for the team.

2022-10-17 09:03 UTC, oleorhagen commented
> @oleorhagen if to be honest I think this approach is more unified than using `gobinarycoverage` due to it's used everywhere else (mender-cli, all backend services...). Obviously the result is the same, but unification is valuable for the team.

You can make the decision here yourself. 

I would favour the gobinarycoverage approach, because it's already in-place, and we would not duplicate functionality.

2022-10-19 09:11 UTC, lluiscampos commented
Close in favor of #435?

2022-10-19 10:14 UTC, closed without merging