chore: Set required golang version to 1.17 and update golang.org/x/crypto to v0.6.0
mendersoftware/mender-artifact pull request #471
Opened 2023-02-22 13:51 UTC by lluiscampos

2023-02-22 14:01 UTC, lluiscampos commented
@mender-test-bot start pipeline

2023-02-22 14:29 UTC, oleorhagen requested changes
What is the `go` version on `Kirkstone` these days?

2023-02-22 14:48 UTC, lluiscampos commented
> What is the `go` version on `Kirkstone` these days?

1.17

Note that we already require 1.17, the source code does not compile with golang 1.16 or earlier.

2023-02-23 09:03 UTC, kacf approved these changes

2023-02-23 09:41 UTC, oleorhagen approved these changes

2023-02-23 09:42 UTC, merged