fix: fixed singing artifact via symlink
mendersoftware/mender-artifact pull request #659
Opened 2024-12-30 09:23 UTC by bahaa-ghazal

Changelog: Title
Ticket: MEN-3410

2025-01-06 09:26 UTC, lluiscampos reviewed
Can you add a test? :pray:

2025-01-06 10:09 UTC, lluiscampos approved these changes
Thank you!

There are some static issues that you need to fix, but the code looks good :rocket:

2025-01-07 14:23 UTC, danielskinstad requested changes
Some comments about the newest commit :), you can see [this](https://github.com/mendersoftware/mendertesting/blob/master/commitlint/grammar.md) for when to use what
* The error formatting fixes some static checks, right? Fixes are generally reserved for bugs in the code
* I don't think the format refactoring commit warrants a changelog entry, so I would set it to `None` instead of `Title`.  
* Typo `erorrs` instead of `errors` 

And a small comment/suggestion regarding closing, otherwise I think it looks good :smile:

2025-01-07 14:23 UTC, danielskinstad commented on cli/sign.go
> -	defer f.Close()
I think keeping this defer here and adding a new `defer f.Close()` right after the new `Open` as it's done here is a bit more clear

2025-01-07 14:23 UTC, danielskinstad commented on cli/sign.go
>  		return cli.NewExitError("Could not get artifact file stat", 1)
The file is not closed here, but keeping the old defer right after would solve it

2025-01-07 14:23 UTC, danielskinstad commented on cli/sign.go
> +		}
I would suggest having a second defer here, and remove the one right below this, as I mentioned above

2025-01-09 09:51 UTC, merged